#List of keywords, nouns, verbs,... that are of interest for reporting_obligation detection

#subject detection:
NO_DETERMINER_ARG2_KEYWORDS = "EBA|ESMA|ECB|EIF|EIB|EIOPA|ESRB|BIS|FSA|PRA|EIOPA|FSB|SRB|FMI|IRSG|OPSG|AMICE|(member )?state|(senior |upper |lower )?management|(office )?(staff|personnel)|(US |American )?(Senate|Congress)|someone|somebody"
SINGULAR_ARG2_KEYWORDS = "Commission|Institution|EBA|European|Parliament|Council|Senate|ESMA|ECB|EIF|EIB|EIOPA|ESRB|BIS|FSA|PRA|EIOPA|FSB|SRB|CCP|SFT|MMF|ETF|REIT|FMI|IORP|ODTI|G-SIB|G-SIFI|CMG|CSD|AIF|NCA|RCA|((competent|resolution||national|regional) )?authority|government|entity|(member )?state|(central )?bank|party|counterparty|(senior |upper |lower )?management|provider|originator|firm|seller|buyer|agent|lawyer|(control |audit(ing)? )unit|group|member( state)?|central body|head of (the )?[^ ]+|company|organization|organisation|committee|supervisor|personnel|staff|actuary|accountant|manager|person|lender|issuer|leader|customer|individual|association|team|corporation|enterprise|university|foundation|intermediary|insurer|borrower|depositor|(bond|policy)holder|liquidator|debtor|creditor|transferor|transferee|distributor|broker|custodian|client|investor|agency|subsidiary|(financial )?conglomerate|competitor"
PLURAL_ARG2_KEYWORDS  = "Commissions|Institutions|Parliaments|Councils|Senates|CCPs|SFTs|MMFs|ETFs|REITs|FMIs|IORPs|ODTIs||G-SIBs|G-SIFIs|CMGs|CSDs|AIFs|NCAs|RCAs|((competent|resolution|national|regional) )?authorities|governments|entities|(member )?states|(central )?banks|parties|counterparties|(senior |upper |lower )?managements|providers|originators|firms|sellers|buyers|agents|lawyers|(control |audit(ing)? )units|groups|members?( states)?|central bodies|heads of (the )?[^ ]+|companies|organizations|organisations|committees|supervisors||personnels|staffs|actuaries|accountants|managers|persons|people|lenders|issuers|leaders|customers|individuals|associations|teams|corporations|enterprises|universities|foundations|intermediaries|insurers|borrowers|depositors|(bond|policy)holders|liquidators|debtors|creditors|transferors|transferee|distributors|brokers|custodians|clients|investors|agencies|subsidiaries||(financial )?conglomerates|competitors"
ALL_ARG2_KEYWORDS = SINGULAR_ARG2_KEYWORDS + '|' + PLURAL_ARG2_KEYWORDS
PLURAL_OR_NODET_ARG2_KEYWORDS = PLURAL_ARG2_KEYWORDS + '|' + NO_DETERMINER_ARG2_KEYWORDS

#verbs and nouns related to obligations...:

INTERESTING_VERBS = "notify|notifies|notified|notifying|inform|informs|informed|informing|report|reports|reported|reporting|provide|provides|provided|providing|submit|submits|submitted|submitting|demonstrate|demonstrates|demonstrated|demonstrating|prove|proves|proved|proving|communicate|communicates|communicated|communicating|send|sends|sent|sending|issue|issues|issued|issuing|publish|publishes|published|publishing|state|disclose|discloses|disclosed|share|shares|shared|document|documents|documented|review|reviews|reviewed|monitor|monitors|monitored|audit|audits|audited|transmit|transmits|transmitted|collect|collects|collected|fill|fills|filled|analyze|analyzes|analyzed|analyse|analyses|analysed|assess|assesses|assessed|alert|alerts|alerted|gather|gathers|gathered|declare|declares|declared|file|files|filed|deliver|delivers|delivered|supply|supplies|supplied|record|records|recorded|maintain|maintains|maintained|record|recorded|compile|compiled".split('|')
OBLIGATION_VERBS = "report|reports|notify|notifies|inform|informs|send|sends|submits|disclose|discloses|alert|alerts".split('|')
INTERESTING_NOUNS = "review|audit|disclosure|report|documentation|plan|system|procedure|process|processes|analysis|analyses|assessment|evaluation|This material|This document".split('|')
OBLIGATION_NOUNS = "review|audit|disclosure|report|documentation".split('|')
INTERESTING_NOUNS_VALID_VERBS_DIRECT = "carry|carried|conduct|conducted|repeat|repeated|perform|performed|produce|produced|implement|implemented|prepare|prepared|subject|subjected|draw|drawn|write|written".split('|')
INTERESTING_NOUNS_VALID_VERBS_SUBJ  = "include|included|comprise|comprised|consist|consisted|address|addressed|support|supported|meet|met|specify|specified|capture|captured|incorporate|incorporated|contain|contained|enable|enabled|allow|allowed|make|made".split('|')

PENDING_LOCATION_TYPES=[['part ','annex '],['title '],['chapter '],['section '],['sub-section '],['article ']]